name: AdNauseam release

on:
  create:
    branches: master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for creating release
    strategy:
      matrix:
        node-version: [18.x]
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Clone uAssets
        run: |
          tools/pull-assets.sh
      - name: Get release information
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build MV2 packages
        run: |
          tools/make-chromium.sh ${{ env.VERSION }}
          tools/make-firefox.sh ${{ env.VERSION }}
      - name: Assemble release notes
        run: |
          > release.body.txt
          grep -m1 -B10000 -- "----------" CHANGELOG.md >> release.body.txt
          sed -e 's!%version%!${{ env.VERSION }}!g' .github/workflows/RELEASE.HEAD.md >> release.body.txt
          cp release.body.txt dist/build/release.body.txt
      - name: Upload builds
        id: upload_build_artifacts
        uses: actions/upload-artifact@v4
        with:
         name: build
         path: dist/build/
      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          draft: true
          prerelease: true
          body_path: release.body.txt
          files: |
            dist/build/uBlock0_${{ env.VERSION }}.chromium.zip
            dist/build/uBlock0_${{ env.VERSION }}.firefox.xpi
